version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_faisal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal-network

  web:
    build: ./backend
    container_name: web_faisal
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./frontend:/usr/src/frontend
    depends_on:
      - db
    networks:
      - internal-network

  snort:
    build: ./snort
    container_name: snort_faisal
    privileged: true 
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080" 
    networks:
      - dmz-network
      - internal-network

  user:
    image: alpine:latest
    container_name: user_faisal
    command: sh -c "apk add --no-cache curl iputils && tail -f /dev/null"
    networks:
      - dmz-network

volumes:
  db_data:

networks:
  dmz-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true 